name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set script executable
        run: sudo chmod +x ./CICD/deploy.sh

      - name: Execute Deployment Script
        run: sudo ./CICD/deploy.sh
