name: Update and Deploy Workflow

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permission
        run: sudo chmod +x deploy.sh

      - name: Run deploy script
        run: sudo ./deploy.sh
